services:
  core-keeper:
    image: escaping/core-keeper-dedicated:latest
    container_name: core-keeper-dedicated
    restart: unless-stopped
    stop_grace_period: 2m
    # Port is only needed if using direct connection mode
    # ports:
    #   - "$SERVER_PORT:$SERVER_PORT/udp"
    volumes:
      - /host/path/to/server-files:/home/steam/core-keeper-dedicated
      - /host/path/to/server-data:/home/steam/core-keeper-data
    env_file:
      - path: core.env
        required: false
